import './styles.css';

type Risk = 'SAFE' | 'CONFIRM' | 'BLOCKED';
type Status = 'ok' | 'at-risk' | 'updated' | 'cancelled';
type ToolName = 'calendar.update_event' | 'transport.reschedule_pickup' | 'transport.switch_to_rideshare' | 'tasks.update' | 'household.update_routine' | 'delivery.reschedule' | 'reservations.modify' | 'messaging.send' | 'contacts.lookup';

type Item = { id: string; title: string; detail: string; time: string; status: Status; anchor?: boolean };
type Step = { id: string; title: string; tool: ToolName; rationale: string; risk: Risk; before: string; after: string; itemId?: string; consequence?: string; status: 'pending' | 'running' | 'done' | 'awaiting' | 'skipped' | 'blocked'; previous?: Item };
type Audit = { id: string; title: string; tool: ToolName; rationale: string; before: string; after: string; status: string; previous?: Item; itemId?: string };
type Scenario = { id: string; label: string; prompt: string; items: Item[]; steps: (prompt: string) => Step[] };
type State = { scenarioId: string; items: Item[]; plan: Step[]; audit: Audit[]; messages: { role: 'user' | 'agent'; text: string }[]; recovered: boolean };

const STORAGE = 'cascade-github-v1';
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v));
const uid = () => Math.random().toString(36).slice(2, 9);
const clock = (m: number) => { const x = ((m % 1440) + 1440) % 1440; const h = Math.floor(x / 60); return `${h % 12 || 12}:${String(x % 60).padStart(2, '0')} ${h >= 12 ? 'PM' : 'AM'}`; };
const parseHours = (text: string) => { const words: Record<string, number> = { one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8 }; const m = text.toLowerCase().match(/(\d+(?:\.\d+)?|one|two|three|four|five|six|seven|eight)\s*(?:hours?|hrs?)/); if (!m) return 4; return /^\d/.test(m[1]) ? Number(m[1]) : words[m[1]] ?? 4; };
const step = (id: number, title: string, tool: ToolName, rationale: string, risk: Risk, before: string, after: string, itemId?: string, consequence?: string): Step => ({ id:`s${id}`,title,tool,rationale,risk,before,after,itemId,consequence,status:'pending' });

const flightItems: Item[] = [
  {id:'flight',title:'Flight AA184 · MIA → JFK',detail:'Scheduled landing 3:10 PM',time:'3:10 PM',status:'ok',anchor:true},
  {id:'pickup',title:'Airport pickup — Jordan',detail:'Curbside at JFK',time:'3:45 PM',status:'ok'},
  {id:'dog',title:'Dog walker — Nia',detail:'30-minute walk for Juno',time:'5:30 PM',status:'ok'},
  {id:'lights',title:'Arrival routine',detail:'Lights + thermostat',time:'5:00 PM',status:'ok'},
  {id:'grocery',title:'Grocery delivery',detail:'Signature required',time:'6:00–8:00 PM',status:'ok'},
  {id:'dinner',title:'Dinner at Vela',detail:'Table for 2 · $18 late-cancel fee',time:'6:30 PM',status:'ok'},
  {id:'work',title:'Q3 handoff call',detail:'Movable · 3 attendees',time:'8:00 PM',status:'ok'},
  {id:'sam',title:'Sam',detail:'Expecting arrival update',time:'Contact',status:'ok'}
];

function flightSteps(prompt: string): Step[] {
  const delay = Math.round(parseHours(prompt) * 60); const landing = 15*60+10+delay; const pickup = landing+35; const home = pickup+35;
  return [
    step(1,'Resolve family contact','contacts.lookup','Confirm who is waiting on an arrival update.','SAFE','Sam · unresolved','Sam · resolved','sam'),
    step(2,`Reset landing to ${clock(landing)}`,'calendar.update_event','The airline delay re-anchors everything downstream.','SAFE','AA184 · 3:10 PM',`AA184 · ${clock(landing)}`,'flight'),
    step(3,`Move pickup to ${clock(pickup)}`,'transport.reschedule_pickup','Adds a bag-claim buffer.','SAFE','Pickup · 3:45 PM',`Pickup · ${clock(pickup)}`,'pickup'),
    step(4,'Extend dog-walker coverage','tasks.update','Juno cannot absorb the arrival delay.','SAFE','Walk · 5:30 PM',`Walk + feed · ${clock(Math.max(17*60+30,landing-30))}`,'dog'),
    step(5,`Shift arrival routine to ${clock(home-10)}`,'household.update_routine','No point lighting an empty house early.','SAFE','Routine · 5:00 PM',`Routine · ${clock(home-10)}`,'lights'),
    step(6,'Move grocery window','delivery.reschedule','Chilled items need a signature.','SAFE','Delivery · 6–8 PM','Delivery · 8–10 PM','grocery'),
    step(7,'Move Q3 handoff call','calendar.update_event','The call is marked movable.','SAFE','Call · 8:00 PM','Call · 9:30 PM','work'),
    step(8,'Move dinner to 8:45 PM','reservations.modify','The original table is unreachable.','CONFIRM','Dinner · 6:30 PM','Dinner · 8:45 PM','dinner','Changes a held booking; cancelling instead costs $18.'),
    step(9,'Send Sam the new arrival plan','messaging.send','Sam is tracking your arrival.','CONFIRM','No message sent',`Message sent · landing ${clock(landing)}, home ~${clock(home)}`,'sam','Sends a message to an external person and cannot be unsent.')
  ];
}

const scenarios: Scenario[] = [
  {id:'flight',label:'Flight delayed 4 hours',prompt:'My flight is delayed four hours. Keep the rest of my day intact.',items:flightItems,steps:flightSteps},
  {id:'school',label:'School closed unexpectedly',prompt:'School closed unexpectedly — reorganize our morning.',items:[{id:'school',title:'School drop-off',detail:'Closed today',time:'8:00 AM',status:'ok',anchor:true},{id:'standup',title:'Team standup',detail:'Async-friendly',time:'9:00 AM',status:'ok'},{id:'client',title:'Client review',detail:'Hard commitment',time:'11:00 AM',status:'ok'},{id:'sitter',title:'Backup sitter',detail:'$28/hr',time:'Unscheduled',status:'ok'},{id:'sam',title:'Sam',detail:'Co-parent',time:'Contact',status:'ok'}],steps:()=>[step(1,'Drop standup','calendar.update_event','Async notes cover it.','SAFE','9:00 AM','Async notes','standup'),step(2,'Protect client review','calendar.update_event','External hard commitment.','SAFE','11:00 AM','Protected 11:00 AM','client'),step(3,'Book sitter 10 AM–1 PM','tasks.update','Covers the client review.','CONFIRM','Unscheduled','10:00 AM–1:00 PM','sitter','$84 paid care commitment.'),step(4,'Message Sam','messaging.send','Coordinate childcare handoff.','CONFIRM','No message','Message sent','sam','Sends an external message.')]},
  {id:'meeting',label:'Meeting moved 2 hours earlier',prompt:'My meeting moved two hours earlier — protect my prep time and commute.',items:[{id:'meeting',title:'Board review',detail:'Moved earlier',time:'2:00 PM',status:'ok',anchor:true},{id:'prep',title:'Prep block',detail:'90 minutes',time:'12:00 PM',status:'ok'},{id:'drive',title:'Commute downtown',detail:'35 minutes',time:'1:15 PM',status:'ok'},{id:'lunch',title:'Lunch with Priya',detail:'Flexible',time:'12:30 PM',status:'ok'}],steps:()=>[step(1,'Move board review to noon','calendar.update_event','Organizer moved it earlier.','SAFE','2:00 PM','12:00 PM','meeting'),step(2,'Protect prep at 9:40 AM','calendar.update_event','Prep must survive before commute.','SAFE','12:00 PM','9:40 AM','prep'),step(3,'Leave downtown at 11:15 AM','transport.reschedule_pickup','Keeps commute buffer.','SAFE','1:15 PM','11:15 AM','drive'),step(4,'Move lunch to 1:30 PM','reservations.modify','Lunch now collides with review.','CONFIRM','12:30 PM','1:30 PM','lunch','Changes another person’s booking.')]},
  {id:'rain',label:'Heavy rain from 4 PM',prompt:'Heavy rain starts at 4 PM — adjust errands and outdoor plans.',items:[{id:'weather',title:'Heavy rain',detail:'4:00–7:30 PM',time:'4:00 PM',status:'ok',anchor:true},{id:'errand',title:'Hardware store run',detail:'Flexible',time:'4:30 PM',status:'ok'},{id:'soccer',title:'Soccer practice',detail:'Coach decides cancellation',time:'5:00 PM',status:'ok'},{id:'picnic',title:'Rooftop picnic',detail:'Outdoor booking',time:'6:00 PM',status:'ok'}],steps:()=>[step(1,'Pull hardware run to 2:30 PM','tasks.update','Finish before the front arrives.','SAFE','4:30 PM','2:30 PM','errand'),step(2,'Soccer cancellation is coach-controlled','calendar.update_event','Cascade does not control the club.','BLOCKED','Practice · 5:00 PM','No action taken','soccer','Only the club can cancel.'),step(3,'Move picnic indoors','reservations.modify','Outdoor venue is exposed.','CONFIRM','Rooftop · 6:00 PM','Home · 6:00 PM','picnic','Releases the rooftop booking.')]}
];

const scenario = (id: string) => scenarios.find(s=>s.id===id) ?? scenarios[0];
const fresh = (id='flight'): State => ({scenarioId:id,items:clone(scenario(id).items),plan:[],audit:[],messages:[{role:'agent',text:'Context loaded. Tell me what changed and I’ll recover the rest of the day.'}],recovered:false});
let state: State = (()=>{ try { return JSON.parse(localStorage.getItem(STORAGE) || 'null') || fresh(); } catch { return fresh(); }})();
const save = () => localStorage.setItem(STORAGE,JSON.stringify(state));
const item = (id?: string) => state.items.find(i=>i.id===id);
const reversible: Record<ToolName,boolean> = {'contacts.lookup':false,'calendar.update_event':true,'transport.reschedule_pickup':true,'transport.switch_to_rideshare':true,'tasks.update':true,'household.update_routine':true,'delivery.reschedule':true,'reservations.modify':true,'messaging.send':false};

function execute(s: Step) { const current=item(s.itemId); if (current && reversible[s.tool]) s.previous=clone(current); if (current && s.tool!=='contacts.lookup') { current.detail=s.after; current.time=s.after.includes('·')?s.after.split('·').slice(1).join('·').trim():current.time; current.status=s.after.toLowerCase().includes('cancelled')?'cancelled':'updated'; } s.status='done'; state.audit.unshift({id:uid(),title:s.title,tool:s.tool,rationale:s.rationale,before:s.before,after:s.after,status:'executed',previous:s.previous,itemId:s.itemId}); save(); }
function finish(){ state.recovered=true; state.messages.push({role:'agent',text:'Day recovered. Every change is in the receipt, with rollback only where the modeled action is reversible.'}); save(); render(); }
async function runFrom(start=0){ for(let i=start;i<state.plan.length;i++){ const s=state.plan[i]; if(s.risk==='BLOCKED'){s.status='blocked';state.audit.unshift({id:uid(),title:s.title,tool:s.tool,rationale:s.rationale,before:s.before,after:'No action taken',status:'blocked',itemId:s.itemId});save();render();await wait(250);continue;} if(s.risk==='CONFIRM'){s.status='awaiting';save();render();return;} s.status='running';render();await wait(280);execute(s);render();await wait(120);} finish(); }
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function submit(prompt:string){ state.messages.push({role:'user',text:prompt}); const lower=prompt.toLowerCase(); if(state.scenarioId==='flight' && state.recovered && /(rideshare|uber|lyft|taxi)/.test(lower)){state.plan=[step(1,'Switch to rideshare','transport.switch_to_rideshare','Replan from the recovered state.','SAFE','Scheduled pickup','Rideshare · 7:30 PM','pickup'),step(2,'Re-time arrival routine','household.update_routine','New ETA is earlier.','SAFE','Routine · 8:05 PM','Routine · 7:55 PM','lights'),step(3,'Tell Jordan and Sam','messaging.send','Both are tracking logistics.','CONFIRM','No follow-up','Message sent · rideshare','sam','Sends external messages.')]; state.messages.push({role:'agent',text:'Replanning from your current recovered state — not the original schedule.'});}else{state.items=state.items.map(i=>i.anchor?i:{...i,status:i.status==='ok'?'at-risk':i.status}); state.plan=scenario(state.scenarioId).steps(prompt); state.messages.push({role:'agent',text:`${state.plan.length} recovery actions planned. Safe actions run automatically; commitments stop for you.`});} save();render();await runFrom();}
function approve(id:string,skip=false){ const i=state.plan.findIndex(s=>s.id===id); if(i<0)return; const s=state.plan[i]; if(skip){s.status='skipped';state.audit.unshift({id:uid(),title:s.title,tool:s.tool,rationale:'Skipped at approval gate.',before:s.before,after:'No action taken',status:'skipped'});}else execute(s); save();render();void runFrom(i+1); }
function rollback(id:string){ const a=state.audit.find(x=>x.id===id); if(!a?.previous||!a.itemId)return; state.items=state.items.map(i=>i.id===a.itemId?clone(a.previous!):i); a.status='rolled-back'; delete a.previous; save();render(); }

function render(){ const s=scenario(state.scenarioId); const awaiting=state.plan.find(x=>x.status==='awaiting'); document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<main><header><div><strong>Cascade</strong><span>Alexa+ simulation</span></div><button id="reset">Reset</button></header><section class="hero"><small>RECOVER THE PLAN, NOT JUST THE CALENDAR</small><h1>One change. The rest of your day recovers.</h1><p>Cascade coordinates downstream commitments, auto-executes reversible changes, pauses before consequential actions, and leaves an auditable receipt.</p><nav>${scenarios.map(x=>`<button data-scenario="${x.id}" class="${x.id===state.scenarioId?'active':''}">${x.label}</button>`).join('')}</nav><div class="run"><q>${s.prompt}</q><button id="run">Run this disruption →</button></div>${state.recovered&&state.scenarioId==='flight'?'<button id="ride">Actually, I’ll take a rideshare instead</button>':''}</section><section class="grid"><div><article><h2>Conversation</h2>${state.messages.map(m=>`<p class="msg ${m.role}">${m.text}</p>`).join('')}<form id="form"><input id="input" placeholder="Tell Cascade what changed…"><button>Send</button></form></article><article><h2>Recovery execution</h2>${state.plan.length?state.plan.map(x=>`<div class="step ${x.status}"><b>${x.title}</b><span>${x.risk}</span><small>${x.rationale}</small></div>`).join(''):'<p class="muted">No plan yet.</p>'}${awaiting?`<div class="approval"><b>Approval required</b><p>${awaiting.consequence||'This action needs confirmation.'}</p><button data-approve="${awaiting.id}">Approve</button><button data-skip="${awaiting.id}">Skip</button></div>`:''}</article></div><aside><article><h2>Context graph</h2>${state.items.map(i=>`<div class="item ${i.status}"><b>${i.title}</b><small>${i.time} · ${i.status}</small></div>`).join('')}</article><article><h2>Audit receipt</h2>${state.audit.length?state.audit.map(a=>`<div class="audit"><b>${a.title}</b><small>${a.tool} · ${a.status}</small><p>${a.before} → ${a.after}</p>${a.previous?`<button data-roll="${a.id}">↶ Roll back</button>`:''}</div>`).join(''):'<p class="muted">Actions will appear here.</p>'}</article></aside></section></main>`; bind();}
function bind(){ document.querySelector('#run')?.addEventListener('click',()=>void submit(scenario(state.scenarioId).prompt)); document.querySelector('#reset')?.addEventListener('click',()=>{state=fresh(state.scenarioId);save();render();}); document.querySelector('#ride')?.addEventListener('click',()=>void submit('Actually, I’ll take a rideshare instead.')); document.querySelectorAll<HTMLElement>('[data-scenario]').forEach(el=>el.addEventListener('click',()=>{state=fresh(el.dataset.scenario);save();render();})); document.querySelectorAll<HTMLElement>('[data-approve]').forEach(el=>el.addEventListener('click',()=>approve(el.dataset.approve!))); document.querySelectorAll<HTMLElement>('[data-skip]').forEach(el=>el.addEventListener('click',()=>approve(el.dataset.skip!,true))); document.querySelectorAll<HTMLElement>('[data-roll]').forEach(el=>el.addEventListener('click',()=>rollback(el.dataset.roll!))); document.querySelector<HTMLFormElement>('#form')?.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector<HTMLInputElement>('#input');if(input?.value.trim())void submit(input.value.trim());}); }
render();
